# Generated by Django 5.1.6 on 2025-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qdepartment', models.CharField(max_length=100)),
                ('Qyear', models.CharField(max_length=4)),
                ('Qsubject', models.CharField(max_length=100)),
                ('Qquestion', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
