# Generated by Django 5.1.6 on 2025-03-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
